<script>
<?php
/**
 * Filter main UI JS config.
 * @see fl_builder_ui_js_config
 */
echo 'FLBuilderConfig              = ' . FLBuilderUtils::json_encode( apply_filters('fl_builder_ui_js_config', array(
	'adminUrl'                   => admin_url(),
	'ajaxNonce'                  => wp_create_nonce( 'fl_ajax_update' ),
	'builderEnabled'             => get_post_meta( $post_id, '_fl_builder_enabled', true ) ? true : false,
	'colorPresets'               => FLBuilderModel::get_color_presets(),
	'customImageSizeTitles'      => apply_filters( 'image_size_names_choose', array() ),
	'debug'                      => FLBuilder::is_debug(),
	'enabledTemplates'           => 'core',
	'global'                     => $global_settings,
	'help'                       => FLBuilderModel::get_help_button_settings(),
	'homeUrl'                    => home_url(),
	'enqueueMethod'              => FLBuilderModel::get_asset_enqueue_method(),
	'isRtl'                      => is_rtl(),
	'isUserTemplate'             => false,
	'lite'                       => true === FL_BUILDER_LITE,
	'modSecFix'                  => FLBuilderUtils::is_modsec_fix_enabled(),
	'MaxInputVars'               => FL_Debug::safe_ini_get( 'max_input_vars' ),
	'moduleGroups'               => FLBuilderModel::get_module_groups(),
	'nestedColumns'              => ( ! defined( 'FL_BUILDER_NESTED_COLUMNS' ) || FL_BUILDER_NESTED_COLUMNS ),
	'newUser'                    => FLBuilderModel::is_new_user(),
	'pluginUrl'                  => FLBuilder::plugin_url(),
	'relativePluginUrl'          => FLBuilderModel::get_relative_plugin_url(),
	'postId'                     => $post_id,
	'postStatus'                 => get_post_status(),
	'postType'                   => get_post_type(),
	'recentFonts'                => get_option( 'fl_builder_recent_fonts', array() ),
	'services'                   => FLBuilderServices::get_services_data(),
	'safemode'                   => isset( $_GET['safemode'] ) ? true : false,
	'simpleUi'                   => $simple_ui ? true : false,
	'upgradeUrl'                 => FLBuilderModel::get_upgrade_url( array(
		'utm_medium'   => ( true === FL_BUILDER_LITE ? 'bb-lite' : 'bb-demo' ),
		'utm_source'   => 'builder-ui',
		'utm_campaign' => ( true === FL_BUILDER_LITE ? 'top-panel-cta' : 'demo-cta' ),
	) ),
	'userCanEditGlobalTemplates' => FLBuilderUserAccess::current_user_can( 'global_node_editing' ),
	'userCanPublish'             => current_user_can( 'publish_posts' ),
	'userSettings'               => FLBuilderUserSettings::get(),
	'userTemplateType'           => FLBuilderModel::get_user_template_type(),
	'userTemplateIsLeafModule'   => FLBuilderModel::is_post_leaf_module_template(),
	'brandingIcon'               => FLBuilderModel::get_branding_icon(),
	'url'                        => get_permalink(),
	'editUrl'                    => FLBuilderModel::get_edit_url(),
	'loginUrl'                   => wp_login_url( FLBuilderModel::get_edit_url() ),
	'shortlink'                  => add_query_arg( 'fl_builder', '', FLBuilderUtils::get_safe_url( $post_id ) ),
	'previewUrl'                 => add_query_arg( 'fl_builder_preview', '', get_permalink() ),
	'layoutHasDraftedChanges'    => FLBuilderModel::layout_has_drafted_changes(),
	'panelData'                  => FLBuilderUIContentPanel::get_panel_data(),
	'contentItems'               => FLBuilderUIContentPanel::get_content_elements(),
	'deprecations'               => FLBuilderModuleDeprecations::get_all_deprecations(),
	'inlineModuleAliases'        => FLBuilderModel::get_inline_module_aliases(),
	'mainMenu'                   => FLBuilder::get_main_menu_data(),
	'keyboardShortcuts'          => FLBuilder::get_keyboard_shortcuts(),
	'isCustomizer'               => is_customize_preview(),
	'showToolbar'                => is_customize_preview() ? false : true,
	/**
	 * Disable outline panel
	 * @since 2.5
	 * @see fl_builder_outline_panel_enabled
	 */
	'showOutlinePanel'           => apply_filters( 'fl_builder_outline_panel_enabled', true ),
	'unrestricted'               => FLBuilderUserAccess::current_user_can( 'unrestricted_editing' ),
	'shouldRefreshOnPublish'     => FLBuilder::should_refresh_on_publish(),
	'googleFontsUrl'             => apply_filters( 'fl_builder_google_fonts_domain', 'https://fonts.googleapis.com/' ) . 'css?family=',
	'wp_editor'                  => FLBuilder::get_wp_editor(),
	'rowResize'                  => FLBuilderModel::get_row_resize_settings(),
	'notifications'              => FLBuilderNotifications::get_notifications(),
	'notificationsEnabled'       => ( 1 == get_option( '_fl_builder_notifications_enabled' ) ) ? true : false,
	'isWhiteLabeled'             => FLBuilderModel::is_white_labeled(),
	'inlineEnabled'              => FLBuilderModel::is_inline_enabled(),
	'CheckCodeErrors'            => FLBuilderModel::is_codechecking_enabled(),
	'AceEditorSettings'          => FLBuilderModel::ace_editor_settings(),
	'optionSets'                 => apply_filters( 'fl_builder_shared_option_sets', array() ),
	'presets'                    => FLBuilderSettingsPresets::get_presets(),
	'FontWeights'                => FLBuilderFonts::get_font_weight_strings(),
	/**
	 * Enable/disable usage stats collection
	 * @see fl_builder_usage_enabled
	 */
	'statsEnabled'               => get_site_option( 'fl_builder_usage_enabled', false ),
	/**
	 * @see fl_remember_settings_tabs_enabled
	 */
	'rememberTab'                => apply_filters( 'fl_remember_settings_tabs_enabled', true ),
	/**
	 * @see fl_select2_enabled
	 */
	'select2Enabled'             => apply_filters( 'fl_select2_enabled', true ),
	/**
	 * @see fl_media_modal_types
	 */
	'uploadTypes'                => apply_filters( 'fl_media_modal_types', array(
		'image'      => 'image',
		'video'      => 'video',
		'videoTypes' => 'mp4,m4v,webm',
	) ),
	/**
	 * @see fl_builder_recent_icons
	 */
	'recentIcons'                => apply_filters( 'fl_builder_recent_icons', get_option( 'fl_plugin_recent_icons', array() ) ),
	'themerLayoutsUrl'           => admin_url( '/edit.php?post_type=fl-theme-layout' ),
	'userCaps'                   => array(
		'unfiltered_html'        => FLBuilderModel::user_has_unfiltered_html(),
		'canUpload'              => current_user_can( 'upload_files' ),
		'global_unfiltered_html' => defined( 'DISALLOW_UNFILTERED_HTML' ) && DISALLOW_UNFILTERED_HTML ? true : false,
	),
	/**
	 * @see fl_node_labels_enabled
	 */
	'node_labels_disabled'       => apply_filters( 'fl_node_labels_disabled', false ),
	/**
	 * @see fl_node_labels_separator
	 */
	'node_labels_separator'      => apply_filters( 'fl_node_labels_separator', ' - ' ),
	/**
	 * CSS to ignore during responsive preview
	 * @see fl_builder_responsive_ignore
	 */
	'responsiveIgnore'           => apply_filters( 'fl_builder_responsive_ignore', array(
		'fl-builder-preview',
		'fl-theme-builder',
		'/wp-includes/',
		'/wp-admin/',
		'admin-bar-inline-css',
		'ace-tm',
		'ace_editor.css',
	)),
	'wooActive'                  => class_exists( 'WooCommerce' ) ? true : false,
	'uploadPath'                 => ( get_option( 'upload_path' ) && get_option( 'upload_path' ) != 'wp-content/uploads' ) ? true : false,
	'uploadUrl'                  => admin_url( 'options-media.php' ),
	'iframeEnabled'              => FLBuilderUIIFrame::is_enabled(),
	'nodeCategoies'              => FLBuilderUISettingsForms::get_node_categories(),
	'responsiveFields'           => array(
		'align',
		'border',
		'color',
		'gradient',
		'dimension',
		'unit',
		'photo',
		'select',
		'typography',
		'text',
		'button-group',
		'aspect-ratio',
		'grid-tracklist',
		'grid-area',
		'grid-auto-flow',
		'flex',
		'justify',
		'size',
		'background',
	),
	'collapseSectionsDefault'    => apply_filters( 'fl_builder_ui_collapse_sections', false ),
	/**
	 * @see fl_builder_default_image_select_size
	 */
	'defaultImageSize'           => apply_filters( 'fl_builder_default_image_select_size', 'full' ),
	'useExperimentalColorPicker' => true,
) ) ) . ';';


/**
 * Filter UI JS Strings.
 * @see fl_builder_ui_js_strings
 */
echo 'FLBuilderStrings             = ' . FLBuilderUtils::json_encode( apply_filters('fl_builder_ui_js_strings', array(
	'copiedToClipboard'              => esc_attr__( 'Copied to clipboard!', 'satori-studio' ),
	'saveGlobalColorsWarning'        => esc_attr__( 'Changes to Global Colors must be saved first before modifying Global Elements. Would you like to save now?', 'satori-studio' ),
	'deleteGlobalColorsWarning'      => esc_attr__( 'Any elements that were assigned to use this color will no longer be using this color.', 'satori-studio' ),
	'actionsLightboxTitle'           => esc_attr__( 'What would you like to do?', 'satori-studio' ),
	/* translators: %s: field name */
	'addField'                       => esc_attr_x( 'Add %s', 'Field name to add.', 'satori-studio' ),
	/* translators: %s: preset color code */
	'alreadySaved'                   => esc_attr_x( '%s is already a saved preset.', '%s is the preset hex color code.', 'satori-studio' ),
	'audioSelected'                  => esc_attr__( 'Audio File Selected', 'satori-studio' ),
	/* translators: %d: number of files selected */
	'audioSelectedNum'               => esc_attr__( '%d Audio File Selected', 'satori-studio' ),
	'audiosSelected'                 => esc_attr__( 'Audio Files Selected', 'satori-studio' ),
	/* translators: %d: number of files selected (plural) */
	'audiosSelectedNum'              => esc_attr__( '%d Audio Files Selected', 'satori-studio' ),
	'blank'                          => esc_attr__( 'Blank', 'satori-studio' ),
	'cancel'                         => esc_attr__( 'Cancel', 'satori-studio' ),
	'reset'                          => esc_attr__( 'Reset', 'satori-studio' ),
	'resetSettingsMessage'           => esc_attr__( 'Do you really want to reset these changes? All of your changes will be lost.', 'satori-studio' ),
	'changeTemplate'                 => esc_attr__( 'Change Template', 'satori-studio' ),
	'changeTemplateMessage'          => esc_attr__( 'Warning! Changing the template will replace your existing layout. Do you really want to do this?', 'satori-studio' ),
	'colorPresets'                   => esc_attr__( 'Color Presets', 'satori-studio' ),
	'colorPicker'                    => esc_attr__( 'Color Picker', 'satori-studio' ),
	'codeError'                      => esc_attr__( 'This code has errors. We recommend you fix them before saving.', 'satori-studio' ),
	'codeerrorhtml'                  => esc_attr__( 'You cannot add <script>, <iframe> or <meta> tags here.', 'satori-studio' ),
	'codeErrorFix'                   => esc_attr__( 'Fix Errors', 'satori-studio' ),
	'codeErrorIgnore'                => esc_attr__( 'Save With Errors', 'satori-studio' ),
	'codeErrorDetected'              => esc_html__( 'We detected a possible issue here:', 'satori-studio' ),
	'childColumn'                    => esc_attr__( 'Child Column', 'satori-studio' ),
	'collapse_all'                   => esc_attr__( 'Collapse All', 'satori-studio' ),
	'column'                         => esc_attr__( 'Column', 'satori-studio' ),
	'columnGroup'                    => esc_attr__( 'Group', 'satori-studio' ),
	'copy'                           => esc_attr__( 'Copy', 'satori-studio' ),
	'contentSliderSelectLayout'      => esc_attr__( 'Please select either a background layout or content layout before submitting.', 'satori-studio' ),
	'contentSliderTransitionWarn'    => esc_attr__( 'Transition value should be lower than Delay value.', 'satori-studio' ),
	'countdownDateisInThePast'       => esc_attr__( 'Error! Please enter a date that is in the future.', 'satori-studio' ),
	'delete'                         => esc_attr__( 'Delete', 'satori-studio' ),
	'deleteAccount'                  => esc_attr__( 'Remove Account', 'satori-studio' ),
	'deleteAccountWarning'           => esc_attr__( 'Are you sure you want to remove this account? Other modules that are connected to it will be affected.', 'satori-studio' ),
	'deleteColumnMessage'            => esc_attr__( 'Do you really want to delete this column?', 'satori-studio' ),
	'deleteColumnGroupMessage'       => esc_attr__( 'Do you really want to delete this column group?', 'satori-studio' ),
	'deleteFieldMessage'             => esc_attr__( 'Do you really want to delete this item?', 'satori-studio' ),
	'deleteModuleMessage'            => esc_attr__( 'Do you really want to delete this module?', 'satori-studio' ),
	'deleteRowMessage'               => esc_attr__( 'Do you really want to delete this row?', 'satori-studio' ),
	'deleteTemplate'                 => esc_attr__( 'Do you really want to delete this template?', 'satori-studio' ),
	'deleteGlobalTemplate'           => esc_attr__( 'WARNING! You are about to delete a global template that may be linked to other pages. Do you really want to delete this template and unlink it?', 'satori-studio' ),
	'discard'                        => esc_attr__( 'Discard Changes and Exit', 'satori-studio' ),
	'discardMessage'                 => esc_attr__( 'Do you really want to discard these changes? All of your changes that are not published will be lost.', 'satori-studio' ),
	'done'                           => esc_attr__( 'Done', 'satori-studio' ),
	'draft'                          => esc_attr__( 'Save Changes and Exit', 'satori-studio' ),
	'duplicate'                      => esc_attr__( 'Duplicate', 'satori-studio' ),
	'duplicateLayout'                => esc_attr_x( 'Duplicate Layout', 'Duplicate page/post action label.', 'satori-studio' ),
	/* translators: %s: form field label */
	'editFormField'                  => esc_attr_x( 'Edit %s', '%s stands for form field label.', 'satori-studio' ),
	'editGlobalSettings'             => esc_attr__( 'Global Settings', 'satori-studio' ),
	'editLayoutSettings'             => esc_attr__( 'Layout CSS / Javascript', 'satori-studio' ),
	'emptyMessage'                   => esc_attr__( 'Drop a row layout or module to get started!', 'satori-studio' ),
	'enterValidDay'                  => esc_attr__( 'Error! Please enter a valid day.', 'satori-studio' ),
	'enterValidMonth'                => esc_attr__( 'Error! Please enter a valid month.', 'satori-studio' ),
	'enterValidYear'                 => esc_attr__( 'Error! Please enter a valid year.', 'satori-studio' ),
	'expand_all'                     => esc_attr__( 'Expand All', 'satori-studio' ),
	'errorMessage'                   => esc_attr__( 'SATORI Studio caught the following JavaScript error. If SATORI Studio is not functioning as expected the cause is most likely this error. Please help us by disabling all plugins and testing SATORI Studio while reactivating each to determine if the issue is related to a third party plugin.', 'satori-studio' ),
	'fieldLoading'                   => esc_attr__( 'Field Loading...', 'satori-studio' ),
	'fontAwesome'                    => esc_attr( FLBuilderFontAwesome::error_text() ),
	'fullSize'                       => esc_attr__( 'Full Size', 'satori-studio' ),
	'getHelp'                        => esc_attr__( 'Get Help', 'satori-studio' ),
	'global'                         => esc_attr_x( 'Global', 'Indicator for global node templates.', 'satori-studio' ),
	'globalErrorMessage'             => __( '"{message}" on line {line} of {file}.', 'satori-studio' ),
	'insert'                         => esc_attr__( 'Insert', 'satori-studio' ),
	'large'                          => esc_attr__( 'Large', 'satori-studio' ),
	'manageTemplates'                => esc_attr__( 'Manage Templates', 'satori-studio' ),
	'medium'                         => esc_attr__( 'Medium', 'satori-studio' ),
	'mobile'                         => esc_attr__( 'Small', 'satori-studio' ),
	'module'                         => esc_attr__( 'Module', 'satori-studio' ),
	'moduleTemplateSaved'            => esc_attr__( 'Module Saved!', 'satori-studio' ),
	'move'                           => esc_attr__( 'Move', 'satori-studio' ),
	'newColumn'                      => esc_attr__( 'New Column', 'satori-studio' ),
	'newRow'                         => esc_attr__( 'New Row', 'satori-studio' ),
	'noneColorSelected'              => esc_attr__( 'Please enter a color first.', 'satori-studio' ),
	'noPresets'                      => esc_attr__( 'No color presets found.', 'satori-studio' ),
	'noResultsFound'                 => esc_attr__( 'No results found.', 'satori-studio' ),
	'noSavedRows'                    => esc_attr__( 'No saved rows found.', 'satori-studio' ),
	'noSavedModules'                 => esc_attr__( 'No saved modules found.', 'satori-studio' ),
	'ok'                             => esc_attr__( 'OK', 'satori-studio' ),
	'photoPage'                      => esc_attr__( 'Photo Page', 'satori-studio' ),
	'photoSelected'                  => esc_attr__( 'Photo Selected', 'satori-studio' ),
	/* translators: %d: number of selected */
	'photoSelectedNum'               => esc_attr__( '%d Photo Selected', 'satori-studio' ),
	'photosSelected'                 => esc_attr__( 'Photos Selected', 'satori-studio' ),
	/* translators: %d: number of selected (plural) */
	'photosSelectedNum'              => esc_attr__( '%d Photos Selected', 'satori-studio' ),
	'placeholder'                    => esc_attr__( 'Paste color here...', 'satori-studio' ),
	'placeholderSelect2'             => esc_attr__( 'Pick a font...', 'satori-studio' ),
	'pleaseWait'                     => esc_attr__( 'Please Wait...', 'satori-studio' ),
	/* translators: %s: preset color code */
	'presetAdded'                    => esc_attr_x( '%s added to presets!', '%s is the preset hex color code.', 'satori-studio' ),
	'publish'                        => esc_attr__( 'Publish Changes', 'satori-studio' ),
	'remove'                         => esc_attr__( 'Remove', 'satori-studio' ),
	'removePresetConfirm'            => esc_attr__( 'Are you sure?', 'satori-studio' ),
	/* translators: %s: time diff - 1 day/2 weeks */
	'revisionDate'                   => esc_attr_x( '%s ago', '%s is a time diff such as 1 day or 2 weeks.', 'satori-studio' ),
	/* translators: %s: author name */
	'revisionAuthor'                 => esc_attr_x( 'By %s', '%s is the author name.', 'satori-studio' ),
	'row'                            => esc_attr__( 'Row', 'satori-studio' ),
	'rowSettings'                    => esc_attr__( 'Row Settings', 'satori-studio' ),
	'rowTemplateSaved'               => esc_attr__( 'Row Saved!', 'satori-studio' ),
	'saveCoreTemplate'               => esc_attr__( 'Save Core Template', 'satori-studio' ),
	'save'                           => esc_attr__( 'Save', 'satori-studio' ),
	'saveAs'                         => esc_attr__( 'Save As...', 'satori-studio' ),
	'saveColumn'                     => esc_attr__( 'Save Column', 'satori-studio' ),
	'saveModule'                     => esc_attr__( 'Save Module', 'satori-studio' ),
	'saveRow'                        => esc_attr__( 'Save Row', 'satori-studio' ),
	'saveTemplate'                   => esc_attr__( 'Save Template', 'satori-studio' ),
	'selectAudio'                    => esc_attr__( 'Select Audio', 'satori-studio' ),
	'selectPhoto'                    => esc_attr__( 'Select Photo', 'satori-studio' ),
	'selectPhotos'                   => esc_attr__( 'Select Photos', 'satori-studio' ),
	'selectVideo'                    => esc_attr__( 'Select Video', 'satori-studio' ),
	'settingsHaveErrors'             => esc_attr__( 'These settings have errors. Please correct them before continuing.', 'satori-studio' ),
	'submitForReview'                => esc_attr__( 'Submit for Review', 'satori-studio' ),
	'subscriptionModuleAccountError' => esc_attr__( 'Please select an account before saving.', 'satori-studio' ),
	'subscriptionModuleConnectError' => esc_attr__( 'Please connect an account before saving.', 'satori-studio' ),
	'subscriptionModuleListError'    => esc_attr__( 'Please select a list before saving.', 'satori-studio' ),
	'subscriptionModuleTagsError'    => esc_attr__( 'Please enter at least one tag before saving.', 'satori-studio' ),
	'takeHelpTour'                   => esc_attr__( 'Take a Tour', 'satori-studio' ),
	'templateAppend'                 => esc_attr__( 'Append New Layout', 'satori-studio' ),
	'templateReplace'                => esc_attr__( 'Replace Existing Layout', 'satori-studio' ),
	'templateSaved'                  => esc_attr__( 'Template Saved!', 'satori-studio' ),
	'thumbnail'                      => esc_attr__( 'Thumbnail', 'satori-studio' ),
	'tourNext'                       => esc_attr__( 'Next', 'satori-studio' ),
	'tourEnd'                        => esc_attr__( 'Get Started', 'satori-studio' ),
	'tourTemplatesTitle'             => esc_attr__( 'Choose a Template', 'satori-studio' ),
	'tourTemplates'                  => esc_attr__( 'Get started by choosing a layout template to customize, or build a page from scratch by selecting the blank layout template.', 'satori-studio' ),
	'tourAddRowsTitle'               => esc_attr__( 'Add Rows', 'satori-studio' ),
	'tourAddRows'                    => esc_attr__( 'Add multi-column rows, adjust spacing, add backgrounds and more by dragging and dropping row layouts onto the page.', 'satori-studio' ),
	'tourAddContentTitle'            => esc_attr__( 'Add Content', 'satori-studio' ),
	'tourAddContent'                 => esc_attr__( 'Add new content by dragging and dropping modules or widgets into your row layouts or to create a new row layout.', 'satori-studio' ),
	'tourEditContentTitle'           => esc_attr__( 'Edit Content', 'satori-studio' ),
	'tourEditContent'                => esc_attr__( 'Move your mouse over rows, columns or modules to edit and interact with them.', 'satori-studio' ),
	'tourEditContent2'               => esc_attr__( 'Use the action buttons to perform actions such as moving, editing, duplicating or deleting rows, columns and modules.', 'satori-studio' ),
	'tourAddContentButtonTitle'      => esc_attr__( 'Add More Content', 'satori-studio' ),
	'tourAddContentButton'           => esc_attr__( 'Use the Add Content button to open the content panel and add new row layouts, modules or widgets.', 'satori-studio' ),
	'tourTemplatesButtonTitle'       => esc_attr__( 'Change Templates', 'satori-studio' ),
	'tourTemplatesButton'            => esc_attr__( 'Use the Templates button to pick a new template or append one to your layout. Appending will insert a new template at the end of your existing page content.', 'satori-studio' ),
	'tourOutlinePanelTitle'          => esc_attr__( 'Outline Panel', 'satori-studio' ),
	'tourOutlinePanel'               => esc_attr__( 'The Outline Panel gives you an overview of your page but you can rearrange and delete elements and open their settings.', 'satori-studio' ),
	'tourToolsButtonTitle'           => esc_attr__( 'Helpful Tools', 'satori-studio' ),
	'tourToolsButton'                => esc_attr__( 'The Tools button lets you save a template, duplicate a layout, edit the settings for a layout or edit the global settings.', 'satori-studio' ),
	'tourDoneButtonTitle'            => esc_attr__( 'Publish Your Changes', 'satori-studio' ),
	'tourDoneButton'                 => esc_attr__( "Once you're finished, click the Done button to publish your changes, save a draft or revert back to the last published state.", 'satori-studio' ),
	'tourFinishedTitle'              => esc_attr__( "Let's Get Building!", 'satori-studio' ),
	'tourFinished'                   => esc_attr__( "Now that you know the basics, you're ready to start building! If at any time you need help, click the help icon in the upper right corner to access the help menu. Happy building!", 'satori-studio' ),
	'unloadWarning'                  => esc_attr__( 'The settings you are currently editing will not be saved if you navigate away from this page.', 'satori-studio' ),
	'viewKnowledgeBase'              => esc_attr__( 'View the Knowledge Base', 'satori-studio' ),
	'validateRequiredMessage'        => esc_attr__( 'This field is required.', 'satori-studio' ),
	'schemaAllRequiredMessage'       => esc_attr__( 'All Structured Data fields are required.', 'satori-studio' ),
	'visitForums'                    => esc_attr__( 'Contact Support', 'satori-studio' ),
	'watchHelpVideo'                 => esc_attr__( 'Watch the Video', 'satori-studio' ),
	'welcomeMessage'                 => esc_attr__( 'Welcome! It looks like this might be your first time using the builder. Would you like to take a tour?', 'satori-studio' ),
	'widget'                         => esc_attr__( 'Widget', 'satori-studio' ),
	'widgetsCategoryTitle'           => esc_attr__( 'WordPress Widgets', 'satori-studio' ),
	'uncategorized'                  => esc_attr__( 'Uncategorized', 'satori-studio' ),
	'uploadBlocked'                  => esc_attr__( 'Uploading files is disabled for this user role', 'satori-studio' ),
	'yesPlease'                      => esc_attr__( 'Yes Please!', 'satori-studio' ),
	'savedModuleNotExists'           => esc_attr__( 'Error: module used in Saved module no longer exists.', 'satori-studio' ),
	'noScriptWarn'                   => array(
		'heading' => esc_attr__( 'Settings could not be saved.', 'satori-studio' ),
		// translators: %s : User Role
		'message' => sprintf( esc_attr__( 'These settings contain sensitive code that is not allowed for your user role (%s).', 'fl-builder' ), FLBuilderUtils::get_current_user_role() ),
		'global'  => esc_attr__( 'These settings contain sensitive code that is not allowed as DISALLOW_UNFILTERED_HTML has been set globally via wp-config.', 'satori-studio' ),
		// translators: %s : Link to Docs
		'footer'  => sprintf( esc_attr__( 'See the %s for more information.', 'satori-studio' ), sprintf( '<a style="color:#00A0D2" target="_blank" href="https://docs.wpbeaverbuilder.com/beaver-builder/troubleshooting/common-issues/error-settings-not-saved">%s</a>', __( 'Knowledge Base', 'satori-studio' ), 'fl-builder' ) ),
	),
	'savedStatus'                    => array(
		'saving'               => esc_attr__( 'Saving...', 'satori-studio' ),
		'savingTooltip'        => esc_attr__( 'The layout is currently being saved', 'satori-studio' ),
		'saved'                => esc_attr__( 'Saved', 'satori-studio' ),
		'savedTooltip'         => esc_attr__( 'The layout is saved', 'satori-studio' ),
		'edited'               => esc_attr__( 'Edited', 'satori-studio' ),
		'editedTooltip'        => esc_attr__( 'This layout has unpublished changes', 'satori-studio' ),
		'editedWarning'        => esc_attr__( 'This layout has unpublished changes. If you discard this draft all of your previously unpublished changes will be lost.', 'satori-studio' ),
		'editedWarningDismiss' => esc_attr__( 'Ok, got it!', 'satori-studio' ),
		'noChanges'            => esc_attr__( 'Nothing new to publish', 'satori-studio' ),
		'publishing'           => esc_attr__( 'Publishing Changes', 'satori-studio' ),
		'publishingTooltip'    => esc_attr__( 'Changes being published', 'satori-studio' ),
		'nothingToSave'        => esc_attr__( 'No new changes to save', 'satori-studio' ),
		'hasAlreadySaved'      => esc_attr__( 'Your changes are saved', 'satori-studio' ),
	),
	'typeLabels'                     => array(
		'template' => esc_attr__( 'Template', 'satori-studio' ),
		'module'   => esc_attr__( 'Module', 'satori-studio' ),
		'row'      => esc_attr__( 'Row', 'satori-studio' ),
		'colGroup' => esc_attr__( 'Column Group', 'satori-studio' ),
		'widget'   => esc_attr__( 'Widget', 'satori-studio' ),
	),
	'categoryMeta'                   => array(
		'landing' => array(
			'name' => esc_attr__( 'Landing Pages', 'satori-studio' ),
		),
		'company' => array(
			'name' => esc_attr__( 'Content Pages', 'satori-studio' ),
		),
	),
	'notifications'                  => array(
		'title'   => esc_attr__( "What's New", 'satori-studio' ),
		'loading' => esc_attr__( 'Loading...', 'satori-studio' ),
		'none'    => esc_attr__( 'No Notifications.', 'satori-studio' ),
	),
	'module_import'                  => array(
		'copied' => esc_attr__( 'Copied!', 'satori-studio' ),
		'error'  => esc_attr__( 'Import Error!', 'satori-studio' ),
		'type'   => esc_attr__( 'Missing header or wrong module type!', 'satori-studio' ),
	),
	'i18n'                           => array(
		'Grid'                                         => esc_attr__( 'Grid', 'satori-studio' ),
		'Flex'                                         => esc_attr__( 'Flex', 'satori-studio' ),
		'Flex Row'                                     => esc_attr__( 'Flex Row', 'satori-studio' ),
		'Flex Column'                                  => esc_attr__( 'Flex Column', 'satori-studio' ),
		'Layered'                                      => esc_attr__( 'Layered', 'satori-studio' ),
		'Outline'                                      => esc_attr__( 'Outline', 'satori-studio' ),
		'Query Monitor'                                => esc_attr__( 'Query Monitor', 'satori-studio' ),
		'No content found'                             => esc_attr__( 'No content found', 'satori-studio' ),
		'Add something'                                => esc_attr__( 'Add Something', 'satori-studio' ),
		'to get started'                               => esc_attr__( 'to get started', 'satori-studio' ),
		'Click + to add layers'                        => esc_attr__( 'Click + to add layers', 'satori-studio' ),
		'sRGB'                                         => esc_attr__( 'sRGB', 'satori-studio' ),
		'Presets'                                      => esc_attr__( 'Presets', 'satori-studio' ),
		'Linear'                                       => esc_attr__( 'Linear', 'satori-studio' ),
		'Linear sRGB'                                  => esc_attr__( 'Linear sRGB', 'satori-studio' ),
		'Radial'                                       => esc_attr__( 'Radial', 'satori-studio' ),
		'Conic'                                        => esc_attr__( 'Conic', 'satori-studio' ),
		'OKLAB'                                        => esc_attr__( 'OKLAB', 'satori-studio' ),
		'OKLCH'                                        => esc_attr__( 'OKLCH', 'satori-studio' ),
		'Text'                                         => esc_attr__( 'Text', 'satori-studio' ),
		'Color'                                        => esc_attr__( 'Color', 'satori-studio' ),
		'Gradient'                                     => esc_attr__( 'Gradient', 'satori-studio' ),
		'Photo'                                        => esc_attr__( 'Photo', 'satori-studio' ),
		'Rings'                                        => esc_attr__( 'Rings', 'satori-studio' ),
		'Stripes'                                      => esc_attr__( 'Stripes', 'satori-studio' ),
		'Sunburst'                                     => esc_attr__( 'Sunburst', 'satori-studio' ),
		'Dots'                                         => esc_attr__( 'Dots', 'satori-studio' ),
		'Triangles'                                    => esc_attr__( 'Triangles', 'satori-studio' ),
		'Alpha'                                        => esc_attr__( 'Alpha', 'satori-studio' ),
		'Hue'                                          => esc_attr__( 'Hue', 'satori-studio' ),
		'Clear'                                        => esc_attr__( 'Clear', 'satori-studio' ),
		'Search'                                       => esc_attr__( 'Search', 'satori-studio' ),
		'Mix'                                          => esc_attr__( 'Mix', 'satori-studio' ),
		'Unnamed Pattern'                              => esc_attr__( 'Unnamed Pattern', 'satori-studio' ),
		'Pattern'                                      => esc_attr__( 'Pattern', 'satori-studio' ),
		'Color Space'                                  => esc_attr__( 'Color Space', 'satori-studio' ),
		'Saved Colors'                                 => esc_attr__( 'Saved Colors', 'satori-studio' ),
		'Mix two color values to create a new color'   => esc_attr__( 'Mix two color values to create a new color', 'satori-studio' ),
		'Are you sure you want to delete this preset?' => esc_attr__( 'Are you sure you want to delete this preset?', 'satori-studio' ),
		'Once you choose a color you can save it as a preset by clicking the + button above.' => esc_attr__( 'Once you choose a color you can save it as a preset by clicking the + button above.', 'satori-studio' ),
	),
) ) ) . ';';

FLBuilderFonts::js();

?>
</script>
